trigger: 
- 7febdemo

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'CS-SUBM-0413(58ab7092-9763-44c6-86ea-7c34d636f23e)'
    subscriptionId: '58ab7092-9763-44c6-86ea-7c34d636f23e'
    action: 'Create Or Update Resource Group'
    templateLocation: 'Linked artifact'
    csmFile: 'ARM/storage-account.json'
    csmParametersFile: 'ARM/parameters.json'
    deploymentMode: 'Incremental'
