# AUTHOR: AJ
# PURPOSE: List all files 

# When to run ?
trigger:
- main
- features/*

variables:
    - name: REGION
      value: centralindia

    - name: RG
      value: yaml-pipeline

# where to run ?

# Self Hosted 
# pool:
#   name: Default

stages:
- stage: A
  displayName: Infra Setup
  jobs: 
  - job: A
    pool:
      vmImage: ubuntu-latest

    variables:
    # Variable Group
    - group: infosys

    - name: STR
      value: yamldemo844943
      # str = 8475346


  # - template: ad-pipelines/simple-examples/storage-account/create-template.yml

- stage: B
  displayName: App Setup
  dependsOn: A
  jobs:
    - job: A
      steps:
      - bash: echo 'Wow'
      
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: 'connect-2-Azure'
          KeyVaultName: 'yaml-kv-demo8954'
          SecretsFilter: '*'
          RunAsPreJob: false
        displayName: Downloads secret from Vault

      - task: AzureCLI@2
        inputs:
          azureSubscription: 'connect-2-Azure'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'az sql server create -l $(REGION) -g $(RG) -n myserver -u $(DB-USER) -p $(DB-PSWD)'
        displayName: Create SQL Server


