# AUTHOR: AJ
# PURPOSE: List all files 

# When to run ?
trigger:
- main
- features/*

# where to run ?

# Self Hosted 
# pool:
#   name: Default

stages:
- stage: A
  displayName: Infra Setup
  jobs: 
  - job: A
    pool:
      vmImage: ubuntu-latest

    variables:
    # Variable Group
    - group: infosys

    - name: STR
      value: yamldemo844943
      # str = 8475346

    - name: REGION
      value: centralindia

    - name: RG
      value: yaml-pipeline


  - template: ad-pipelines/simple-examples/storage-account/create-template.yml

- stage: B
  displayName: App Setup
  dependsOn: A
  jobs:
    - job: A
      steps:
      - bash: echo 'Wow'



