# AUTHOR: AJ
# PURPOSE: List all files 

# When to run ?
trigger:
- main
- features/*

# where to run ?

# Self Hosted 
# pool:
#   name: Default

pool:
  vmImage: ubuntu-latest

variables:
# Variable Group
- group: infosys

- name: STR
  value: yamldemo844943
  # str = 8475346

- name: REGION
  value: centralindia

- name: RG
  value: yaml-pipeline

jobs:
- job: A
  steps:
  - bash: 'echo from pipeline => $(STR)'
  - bash: 'echo from Vars Group => $(STR)'
  - bash: 'echo from top-right => $(top-right)'
  

- job: B

  steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'connect-2-Azure'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'az storage account check-name --name $(STR)'
        displayName: Check if Name Valid

      - task: AzureCLI@2
        inputs:
          azureSubscription: 'connect-2-Azure'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'az group create -n $(RG) -l $(REGION)'
        displayName: Create RG

      - task: AzureCLI@2
        inputs:
          azureSubscription: 'connect-2-Azure'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'az storage account create -n $(STR) -g $(RG) -l $(REGION) --sku Standard_LRS'
        displayName: Create Storage Account