# AUTHOR: AJ
# PURPOSE: List all files 

# When to run ?
trigger:
- main
- features/*

# where to run ?

# Self Hosted 
# pool:
#   name: Default

pool:
  vmImage: ubuntu-latest

variables:
# Variable Group
- group: infosys

- name: STR
  value: yamldemo844943
  # str = 8475346

- name: REGION
  value: centralindia

- name: RG
  value: yaml-pipeline

jobs:

- template: ad-pipelines/simple-examples/storage-account/create-template.yml

- job: PipelineJob
  steps:
  - bash: 'echo from pipeline => $(STR)'
  - bash: 'echo from Vars Group => $(STR)'
  - bash: 'echo from top-right => $(top-right)'
  

