### May show time out error but website succesful 

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- template: 0-vars-template.yml

# $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
# If you have a pipeline that produces artifacts, 
# you can consume the artifacts by defining a pipelines resource.
#  Only Azure Pipelines can use the pipelines resource. 
#  You can set triggers for your continuous deployment (CD) workflows on a pipeline resource.

resources:
    
  pipelines:
  - pipeline: app-build # Name of the pipeline resource.
    source: test # The name of the pipeline referenced by this pipeline resource. (as visible in ADO)
    project: test # Required only if the source pipeline is in another project
    branch: main
    trigger: true


steps:
######## you also need to chnage it ################
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '1aaead7b-9db5-46ed-bb03-9111ee33087c'
    definition: '21'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)/artifact'
# **********************************************************

# BOth having repo root in them 
# $(Pipeline.Workspace) = pipeline workspace => /home/vsts/work/1

- bash: |
      unzip *.zip 
      mkdir -p $(Pipeline.Workspace)/build
      cp -r ./* $(Pipeline.Workspace)/build
  workingDirectory: $(Pipeline.Workspace)/artifact/drop

- bash: |
     rm -rf $(Pipeline.Workspace)/build/*.zip
     ls -ltr $(Pipeline.Workspace)/build
- task: AzureCLI@2
  displayName: App-Setting
  inputs:
    azureSubscription: ${{ variables.azureSubscription }}
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az webapp config appsettings set \
          --resource-group $RG \
          --name $NAME \
          --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true
    workingDirectory: '$(Pipeline.Workspace)/artifact'
  env: 
    RG: $(RG)
    REGION: $(REGION)
    NAME: $(NAME)

# for  az webapp deploy
# --src-path
# Path of the artifact to be deployed. Ex: "myapp.zip"
# --target-path
# Absolute path that the artifact should be deployed to. Defaults to "home/site/wwwroot/
- task: AzureCLI@2
  inputs:
    azureSubscription: ${{ variables.azureSubscription }}
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az webapp deploy \
          --name $NAME \
          --resource-group $RG \
          --src-path $(Pipeline.Workspace)/artifact/drop/*.zip
  env: 
    RG: $(RG)
    REGION: $(REGION)
    NAME: $(NAME)