# ------------------------ When to Run -------------------------------------
trigger:
- main
- revision

resources:
  pipelines:
  - pipeline: demo # Name of the pipeline resource.
    source: 'code ready' # The name of the pipeline referenced by this pipeline resource.
    project: CTS # Required only if the source pipeline is in another project
    trigger: true

# ---------------------- Where to Run -----------------------------------
pool:
  vmImage: ubuntu-latest

# pool: 
#  name: your-self-hosted-agent-pool-name

# -------------------------- What to do ---------------------------
steps:
- script: ls -l
  displayName: 'list all files'

- script: |
    chmod +x script.sh
    ./script.sh
    echo third command
  displayName: 'more commands'

- task: Bash@3
  inputs:
    filePath: 'script.sh'
  displayName: Bash File
