# az webapp create -g MyResourceGroup -p MyPlan -n MyUniqueAppName --runtime "PYTHON:3.12"
# az webapp list-runtimes
# 
name: app-build

trigger: none
#- features/arm-deployment

pool:
  vmImage: ubuntu-latest

# variables:
# - template: ad-pipelines/Calculator-YAML/0-vars-template.yml

# - name : RG
#   value: cicd

# - name: NAME
#   value: test656756

# - name: REGION
#   value: centralindia

# - name: azureSubscription-Service-Connection
#   value: Azure Pass - Sponsorship(2d4735f4-61ae-40d4-b1b1-5240916b7d0c)

steps:
- task: ArchiveFiles@2
  displayName: 'Archive Python'
  inputs:
    rootFolderOrFile: 'calculator App - Python'
    # make sure NOT includeRootFolder - Prepend root folder name to archive paths
#     boolean. Default value: true.
    includeRootFolder: false 
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'


# - download: current
#   artifact: WebApp
  

