name: 2-deploy

trigger: none
# - features/arm-deployment

pool:
  vmImage: ubuntu-latest

variables:
# Can use var group / template  here for cross pipeline comm
- name : RG
  value: cicd

- name: NAME
  value: classic-pipeline-876

- name: REGION
  value: centralindia

resources:
    
  pipelines:
  - pipeline: app-build # Name of the pipeline resource.
    source: az-400-codes.git # The name of the pipeline referenced by this pipeline resource. (as visible in ADO)
    project: GO # Required only if the source pipeline is in another project
    branch: features/arm-deployment
    trigger: true


steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '829c7f72-4144-4cda-81a6-483f7b7efaa7'
    definition: '4'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)/artifact'

# BOth having repo root in them 
# $(Pipeline.Workspace) = pipeline workspace => /home/vsts/work/1

- bash: |
      unzip *.zip 
      mkdir -p $(Pipeline.Workspace)/build
      cp -r ./* $(Pipeline.Workspace)/build
  workingDirectory: $(Pipeline.Workspace)/artifact/drop


- bash: |
     ls -ltr $(Pipeline.Workspace)/build

- task: AzureCLI@2
  displayName: App-Setting
  inputs:
    azureSubscription: 'Subscription-1(a43a9c48-19cb-4772-a3b8-79884e338743)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az webapp config appsettings set \
          --resource-group $RG \
          --name $NAME \
          --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true
    workingDirectory: '$(Pipeline.Workspace)/artifact'
  env: 
    RG: $(RG)
    REGION: $(REGION)
    NAME: $(NAME)

# for  az webapp deploy
# --src-path
# Path of the artifact to be deployed. Ex: "myapp.zip"
# --target-path
# Absolute path that the artifact should be deployed to. Defaults to "home/site/wwwroot/
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Subscription-1(a43a9c48-19cb-4772-a3b8-79884e338743)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az webapp deploy \
          --name $NAME \
          --resource-group $RG \
          --src-path $(Pipeline.Workspace)/artifact/drop/*.zip
  env: 
    RG: $(RG)
    REGION: $(REGION)
    NAME: $(NAME)
     
# bekaronly zip reach no unzip no port 
# - task: AzureRmWebAppDeployment@4
#   inputs:
#     ConnectionType: 'AzureRM'
#     azureSubscription: 'Subscription-1(a43a9c48-19cb-4772-a3b8-79884e338743)'
#     appType: 'webAppLinux'
#     WebAppName: '$(NAME)'
#     packageForLinux: '$(Pipeline.Workspace)/artifact/drop'
#     RuntimeStack: 'PYTHON|3.11'
#   env: 
#     RG: $(RG)
#     REGION: $(REGION)
#     NAME: $(NAME)
