name: Docker Image CI-CD

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          # Provide docker hub password - cnda 

  docker:
    runs-on: ubuntu-latest
    needs: login  # Ensures that 'login' job completes before 'docker' job starts
    steps:
      - uses: actions/checkout@v4

      - name: Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build the Docker image
        run: docker build . --file ../docker/nginx.Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/repository_name:${{ github.run_id }}
        working-directory: web-page
        
      - name: Docker Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/repository_name:${{ github.run_id }}
        working-directory: web-page
      
        
      - name: Inspect
        run: |
          docker image inspect ${{ secrets.DOCKERHUB_USERNAME }}/repository_name:${{ github.run_id }}
