name: Deploy 2 Azure

permissions:
  id-token: write
  contents: read
  
on:
  push:
    branches:
      - conflict
  workflow_dispatch: {}

jobs:
   login:
       runs-on: ubuntu-latest
       steps:
       - name: Azure Login
         uses: Azure/login@v2.2.0
         with:
            # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
            # creds: # optional
            # ClientId of the Azure Service principal created.
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            # TenantId of the Azure Service principal created.
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            # Azure subscriptionId
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            # Set this value to true to enable Azure PowerShell Login in addition to Azure CLI login
            # enable-AzPSSession: # optional
            # # Name of the environment. Supported values are azurecloud, azurestack, azureusgovernment, azurechinacloud, azuregermancloud. Default being azurecloud
            # environment: # optional, default is azurecloud
            # # Set this value to true to enable support for accessing tenants without subscriptions
            # allow-no-subscriptions: # optional
            # # Provide audience field for access-token. Default value is api://AzureADTokenExchange
            # audience: # optional, default is api://AzureADTokenExchange
            # # The type of authentication. Supported values are SERVICE_PRINCIPAL, IDENTITY. Default value is SERVICE_PRINCIPAL
            # auth-type: # optional, default is SERVICE_PRINCIPAL
       - name: CLI
         run: |
             az group create -n gh-env-rg -l centralindia
             az network vnet create --name gh-vnet-1 --resource-group gh-env-rg --address-prefix 10.0.0.0/16 --subnet-name subnet-1 --subnet-prefixes 10.0.0.0/24

   # azCli:
   #     runs-on: ubuntu-latest
   #     steps:
   #     - name: Azure CLI Action
   #       uses: Azure/cli@v2.1.0
   #       with:
   #              # Specify the script here
   #              inlineScript: az network vnet create --name gh-vnet-1 --resource-group gh-env-rg --address-prefix 10.0.0.0/16 --subnet-name subnet-1 --subnet-prefixes 10.0.0.0/24
                # Azure CLI version to be used to execute the script. If not provided, latest version is used
                #azcliversion: # optional, default is agentazcliversion
          
